### ISSUE TITLE
Zend action Helper

### ISSUE THREAD

**Issue by ombr** [benjamindulau/Ano_ZFTwig#8]
Hi,

When I call {{ zf.action('index') }} everything is fine, but when I'm using modules, and try for example :

{{zf.action('test','index','admin')}}

I get this error :

Fatal error: Uncaught exception 'Zend_Loader_PluginLoader_Exception' with message 'Plugin by name 'Message' was not found in the registry; used paths:
Zend_Dojo_View_Helper_: Zend/Dojo/View/Helper/
Admin_View_Helper_: /home/ombr/public_html/lls/application/modules/admin/views/helpers/
My_View_Helper_: My/View/Helper/
Zend_View_Helper_: Zend/View/Helper/:/home/ombr/public_html/lls/application/views/helpers/' in /home/ombr/public_html/lls/library/vendors/zend/library/Zend/Loader/PluginLoader.php:412
Stack trace:
#0 /home/ombr/public_html/lls/library/vendors/zend/library/Zend/View/Abstract.php(1182): Zend_Loader_PluginLoader->load('Message')
#1 /home/ombr/public_html/lls/library/vendors/zend/library/Zend/View/Abstract.php(618): Zend_View_Abstract->_getPlugin('helper', 'message')
#2 /home/ombr/public_html/lls/library/vendors/zend/library/Zend/View/Abstract.php(344): Zend_View_Abstract->getHelper('message')
#3 [internal function]: Zend_View_Abstract->__call('message', Array)
#4 [internal function]: Ano_View->message()
#5 /home in /home/ombr/public_html/lls/library/vendors/twig/lib/Twig/Template.php on line 182

Any Idea ??

Thanks

**Comment by ombr** [comment]
Sorry, my fault...
